[package]
name = "generic-observer"
version = "0.1.0"
edition = "2021"
resolver = "2"
path = "src/main.rs"

[[bin]]
name = "normal-observer"
path = "src/main_normal.rs"


[dependencies]
generic-observer-macros = { path = "./generic-observer-macros" }