[package]
name = "generic-observer-macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "generic_observer_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.66" , features = ["full"] }
proc-macro2 = "1.0"